version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      spring-boot:
        patterns:
          - "org.springframework.boot:*"
      testcontainers:
        patterns:
          - "org.testcontainers:*"
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - ci
      - dependencies
